// Centralized site data
window.SITE_DATA = {
  site: {
    name: 'AutoSarge',
    tagline: 'Carros Usados',
    favicon: {
      images: ['images/favicon.ico'],
      type: 'image/x-icon'
    },
    logos: {
      // Logo shown in the top navigation bar
      nav: {
        images: ['images/logo.png'],
        alt: 'AutoSarge Logo'
      }
    }
  },
  contact: {
    phone: '+351918754848',
    phoneDisplay: '+351 918 754 848',
    phone2: '+351912251080',
    phone2Display: '+351 912 251 080',
    email: 'autosarge2005@gmail.com',
    formEndpoint: 'https://formspree.io/f/mldweezn'
  },
  hero: {
    title: 'Encontre o carro dos seus sonhos',
    text: 'As melhores ofertas em carros usados.',
    image: 'images/logo.png',
    alt: 'Logo AutoSarge'
  },
  cars: [
    {
      id: 1,
      name: 'Ford Fusion 1.25 X-Trend',
      year: 2006,
      price: 3590,
      sold: false,
      hidden: false,
      mileage: 140677,
      fuel: 'Diesel',
      transmission: 'Manual',
      images: [
        'images/car1.jpg',
        'images/car1_extra2.jpg',
        'images/car1_extra3.jpg',
        'images/car1_extra4.jpg',
        'images/car1_extra5.jpg',
        'images/car1_extra6.jpg',
        'images/car1_extra7.jpg',
        'images/car1_extra8.jpg',
        'images/car1_extra9.jpg',
        'images/car1_extra10.jpg',
        'images/car1_extra11.jpg',
        'images/car1_extra12.jpg',
        'images/car1_extra13.jpg',
        'images/car1_extra14.jpg',
        'images/car1_extra15.jpg',
        'images/car1_extra16.jpg',
        'images/car1_extra17.jpg',
        'images/car1_extra18.jpg',
        'images/car1_extra19.jpg',
        'images/car1_extra20.jpg',
        'images/car1_extra21.jpg',
        'images/car1_extra22.jpg',
        'images/car1_extra23.jpg',
        'images/car1_extra24.jpg',
        'images/car1_extra25.jpg'
      ],
      features: ['Ar Condicionado', 'Jantes de Liga Leve', 'Comando de rádio no volante', 'Bluetooth']
    },
    {
      id: 2,
      name: 'Opel Astra 1.7 CDTi Cosmo',
      year: 2011,
      price: 5890,
      sold: false,
      hidden: false,
      mileage: 239400,
      fuel: 'Diesel',
      transmission: 'Manual',
      images: [
        'images/car2.jpg',
        'images/car2_extra2.jpg',
        'images/car2_extra3.jpg',
        'images/car2_extra4.jpg',
        'images/car2_extra5.jpg',
        'images/car2_extra6.jpg',
        'images/car2_extra7.jpg',
        'images/car2_extra8.jpg',
        'images/car2_extra9.jpg',
        'images/car2_extra10.jpg',
        'images/car2_extra11.jpg',
        'images/car2_extra12.jpg',
        'images/car2_extra13.jpg',
        'images/car2_extra14.jpg',
        'images/car2_extra15.jpg',
        'images/car2_extra16.jpg',
        'images/car2_extra17.jpg',
        'images/car2_extra18.jpg',
        'images/car2_extra19.jpg',
        'images/car2_extra20.jpg',
        'images/car2_extra21.jpg',
        'images/car2_extra22.jpg',
        'images/car2_extra23.jpg',
        'images/car2_extra24.jpg',
        'images/car2_extra25.jpg'
      ],
      features: ['Alarme origem', 'Sistema navegação', 'Sensores estacionamento frente e trás', 'Faróis LED']
    },
    {
      id: 3,
      name: 'Peugeot Partner 1.6 HDi 100 Cv Premier * ',
      year: 2017,
      price: 9890,
      sold: false,
      hidden: false,
      mileage: 218541,
      fuel: 'Diesel',
      transmission: 'Automática',
      images: [
        'images/car3.jpg',
        'images/car3_extra1.jpg',
        'images/car3_extra2.jpg',
        'images/car3_extra3.jpg',
        'images/car3_extra4.jpg',
        'images/car3_extra5.jpg',
        'images/car3_extra6.jpg',
        'images/car3_extra7.jpg',
        'images/car3_extra8.jpg',
        'images/car3_extra9.jpg',
        'images/car3_extra10.jpg',
        'images/car3_extra11.jpg',
        'images/car3_extra12.jpg',
        'images/car3_extra13.jpg',
        'images/car3_extra14.jpg',
        'images/car3_extra15.jpg',
        'images/car3_extra16.jpg',
        'images/car3_extra17.jpg',
        'images/car3_extra18.jpg',
        'images/car3_extra19.jpg',
        'images/car3_extra20.jpg',
        'images/car3_extra21.jpg',
        
      ],
      features: ['3 Lugares', 'Patilhas da Caixa ao Volante', 'Cruise Control', 'Sistema GPS', 'Apple Carplay e Mirrorlink', 'Sensores Estacionamento com monitor integrado', 'Bola de Reboque removível', 'Start & Stop']
    },
    {
      id: 4,
      name: 'MINI 3 Portas One 1.4 D',
      year: 2004,
      price: 3990,
      sold: false,
      hidden: false,
      mileage: 343211,
      fuel: 'Diesel',
      transmission: 'Manual',
      images: [
        'images/car4.jpg',
        'images/car4_extra1.jpg',
        'images/car4_extra2.jpg',
        'images/car4_extra3.jpg',
        'images/car4_extra4.jpg',
        'images/car4_extra5.jpg',
        'images/car4_extra6.jpg',
        'images/car4_extra7.jpg',
        'images/car4_extra8.jpg',
        'images/car4_extra9.jpg',
        'images/car4_extra10.jpg',
        'images/car4_extra11.jpg',
        'images/car4_extra12.jpg',
        'images/car4_extra13.jpg',
        'images/car4_extra14.jpg',
        'images/car4_extra15.jpg',
        'images/car4_extra16.jpg',
        'images/car4_extra17.jpg',
        'images/car4_extra18.jpg',
        'images/car4_extra19.jpg',
        'images/car4_extra20.jpg',
        'images/car4_extra21.jpg',
      ],
      features: ['Rádio', 'Controlo de tração', 'Controlo de estabilidade']
    },
    {
      id: 5,
      name: 'Toyota Prius 1.8 Premium',
      year: 2010,
      price: 8790,
      sold: false,
      hidden: false,
      mileage: 168563,
      fuel: 'Híbrido (Gasolina)',
      transmission: 'Automático',
      images: [
        'images/car5-new.jpg',
        'images/car5_extra2.jpg',
        'images/car5_extra3.jpg',
        'images/car5_extra4.jpg',
        'images/car5_extra5.jpg',
        'images/car5_extra6.jpg',
        'images/car5_extra7.jpg',
        'images/car5_extra8.jpg',
        'images/car5_extra9.jpg',
        'images/car5_extra10.jpg',
        'images/car5_extra11.jpg',
        'images/car5_extra12.jpg',
        'images/car5_extra13.jpg',
        'images/car5_extra14.jpg',
        'images/car5_extra15.jpg',
        'images/car5_extra16.jpg',
        'images/car5_extra17.jpg',
        'images/car5_extra18.jpg',
        'images/car5_extra19.jpg',
        'images/car5_extra20.jpg',
        'images/car5_extra21.jpg',
        'images/car5_extra22.jpg',
        'images/car5_extra23.jpg',
        'images/car5_extra24.jpg',
        'images/car5_extra25.jpg',
        'images/car5_extra26.jpg',
        'images/car5_extra27.jpg',
        'images/car5_extra28.jpg',
        'images/car5_extra29.jpg',
        'images/car5_extra30.jpg',
        'images/car5_extra31.jpg',
        'images/car5_extra32.jpg',
        'images/car5_extra33.jpg',
        'images/car5_extra34.jpg',
        'images/car5_extra35.jpg',
      ],
      features: ['Híbrido']
    },
    {
      id: 6,
      name: 'Volkswagen Transporter 2.5 Tdi 102cv Califórnia / Westfalia',
      year: 1997,
      price: 18990,
      sold: false,
      hidden: false,
      mileage: 340000,
      fuel: 'Diesel',
      transmission: 'Manual',
      images: [
        'images/car6-new.jpg',
        'images/car6_extra2.jpg',
        'images/car6_extra3.jpg',
        'images/car6_extra4.jpg',
        'images/car6_extra5.jpg',
        'images/car6_extra6.jpg',
        'images/car6_extra7.jpg',
        'images/car6_extra8.jpg',
        'images/car6_extra9.jpg',
        'images/car6_extra10.jpg',
        'images/car6_extra11.jpg',
        'images/car6_extra12.jpg',
        'images/car6_extra13.jpg',
        'images/car6_extra14.jpg',
        'images/car6_extra15.jpg',
        'images/car6_extra16.jpg',
        'images/car6_extra17.jpg',
      ],
      features: ['Painel Solar', 'Discos novos + pastilhas novas', 'Distribuição e Bomba de Água nova', 'Embraiagem e bomba nova', 'Bateria Auxiliar nova', 'Interiores de origem', 'Fogão a Gás com inspeção técnica aprovada', 'Frigorífico a funcionar corretamente']
    },
    {
      id: 7,
      name: 'Audi Q5',
      year: 2020,
      price: 48900,
      sold: false,
      hidden: true,
      mileage: 35000,
      fuel: 'Diesel',
      transmission: 'Manual',
      images: [
        'images/car7.jpg',
        'images/car7_extra2.jpg',
        'images/car7_extra3.jpg',
        'images/car7_extra4.jpg',
        'images/car7_extra5.jpg',
        'images/car7_extra6.jpg',
        'images/car7_extra7.jpg',
        'images/car7_extra8.jpg',
        'images/car7_extra9.jpg',
        'images/car7_extra10.jpg',
        'images/car7_extra11.jpg',
        'images/car7_extra12.jpg',
        'images/car7_extra13.jpg',
        'images/car7_extra14.jpg',
        'images/car7_extra15.jpg',
        'images/car7_extra16.jpg',
        'images/car7_extra17.jpg',
        'images/car7_extra18.jpg',
        'images/car7_extra19.jpg',
        'images/car7_extra20.jpg',
        'images/car7_extra21.jpg',
        'images/car7_extra22.jpg',
        'images/car7_extra23.jpg',
        'images/car7_extra24.jpg',
        'images/car7_extra25.jpg'
      ],
      features: ['Tração Quatro', 'Navegação', 'Bancos em Pele', 'Teto Panorâmico']
    },
    {
      id: 8,
      name: 'BMW X1',
      year: 2019,
      price: 32900,
      sold: false,
      hidden: true,
      mileage: 54000,
      fuel: 'Gasolina',
      transmission: 'Manual',
      images: [
        'images/car8.jpg',
        'images/car8_extra2.jpg',
        'images/car8_extra3.jpg',
        'images/car8_extra4.jpg',
        'images/car8_extra5.jpg',
        'images/car8_extra6.jpg',
        'images/car8_extra7.jpg',
        'images/car8_extra8.jpg',
        'images/car8_extra9.jpg',
        'images/car8_extra10.jpg',
        'images/car8_extra11.jpg',
        'images/car8_extra12.jpg',
        'images/car8_extra13.jpg',
        'images/car8_extra14.jpg',
        'images/car8_extra15.jpg',
        'images/car8_extra16.jpg',
        'images/car8_extra17.jpg',
        'images/car8_extra18.jpg',
        'images/car8_extra19.jpg',
        'images/car8_extra20.jpg',
        'images/car8_extra21.jpg',
        'images/car8_extra22.jpg',
        'images/car8_extra23.jpg',
        'images/car8_extra24.jpg',
        'images/car8_extra25.jpg'
      ],
      features: ['Sensores Dianteiros', 'Câmara Traseira', 'Apple CarPlay', 'Android Auto']
    },
    {
      id: 9,
      name: 'Mercedes A200',
      year: 2021,
      price: 29900,
      sold: false,
      hidden: true,
      mileage: 22000,
      fuel: 'Gasolina',
      transmission: 'Manual',
      images: [
        'images/car9.jpg',
        'images/car9_extra2.jpg',
        'images/car9_extra3.jpg',
        'images/car9_extra4.jpg',
        'images/car9_extra5.jpg',
        'images/car9_extra6.jpg',
        'images/car9_extra7.jpg',
        'images/car9_extra8.jpg',
        'images/car9_extra9.jpg',
        'images/car9_extra10.jpg',
        'images/car9_extra11.jpg',
        'images/car9_extra12.jpg',
        'images/car9_extra13.jpg',
        'images/car9_extra14.jpg',
        'images/car9_extra15.jpg',
        'images/car9_extra16.jpg',
        'images/car9_extra17.jpg',
        'images/car9_extra18.jpg',
        'images/car9_extra19.jpg',
        'images/car9_extra20.jpg',
        'images/car9_extra21.jpg',
        'images/car9_extra22.jpg',
        'images/car9_extra23.jpg',
        'images/car9_extra24.jpg',
        'images/car9_extra25.jpg'
      ],
      features: ['MBUX', 'LED High Performance', 'Assistente Faixa', 'Aquecimento Bancos']
    },
    {
      id: 10,
      name: 'Renault Clio',
      year: 2017,
      price: 10900,
      sold: false,
      hidden: true,
      mileage: 78000,
      fuel: 'Gasolina',
      transmission: 'Manual',
      images: [
        'images/car10.jpg',
        'images/car10_extra2.jpg',
        'images/car10_extra3.jpg',
        'images/car10_extra4.jpg',
        'images/car10_extra5.jpg',
        'images/car10_extra6.jpg',
        'images/car10_extra7.jpg',
        'images/car10_extra8.jpg',
        'images/car10_extra9.jpg',
        'images/car10_extra10.jpg',
        'images/car10_extra11.jpg',
        'images/car10_extra12.jpg',
        'images/car10_extra13.jpg',
        'images/car10_extra14.jpg',
        'images/car10_extra15.jpg',
        'images/car10_extra16.jpg',
        'images/car10_extra17.jpg',
        'images/car10_extra18.jpg',
        'images/car10_extra19.jpg',
        'images/car10_extra20.jpg',
        'images/car10_extra21.jpg',
        'images/car10_extra22.jpg',
        'images/car10_extra23.jpg',
        'images/car10_extra24.jpg',
        'images/car10_extra25.jpg'
      ],
      features: ['Bluetooth', 'Ar Condicionado', 'Limitador Velocidade', 'Sensor Chuva']
    }
  ]
};
